define(["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    /****
     * Object containing names for basically every usable keyboard key.
     ****/
    exports.Keys = {
		//Mouse and Touch
		leftButton:1,
		middleButton:2,
		rightButton:3,
        a: 65,
        b: 66,
        c: 67,
        d: 68,
        e: 69,
        f: 70,
        g: 71,
        h: 72,
        i: 73,
        j: 74,
        k: 75,
        l: 76,
        m: 77,
        n: 78,
        o: 79,
        p: 80,
        q: 81,
        r: 82,
        s: 83,
        t: 84,
        u: 85,
        v: 86,
        w: 87,
        x: 88,
        y: 89,
        z: 90,
        zero: 48,
        one: 49,
        two: 50,
        three: 51,
        four: 52,
        five: 53,
        six: 54,
        seven: 55,
        eight: 56,
        nine: 57,
        numPadZero: 96,
        numPadOne: 97,
        numPadTwo: 98,
        numPadThree: 99,
        numPadFour: 100,
        numPadFive: 101,
        numPadSix: 102,
        numPadSeven: 103,
        numPadEight: 104,
        numPadNine: 105,
        numPadAsterisk: 106,
        numPadPlus: 107,
        numPadMinus: 109,
        numPadPeriod: 110,
        numPadForwardSlash: 111,
        minus: 189,
        equals: 187,
        space: 32,
        enter: 13,
        shift: 16,
        crtl: 17,
        alt: 18,
        tab: 9,
        capsLock: 20,
        backspace: 8,
        escape: 27,
        insert: 45,
        delete: 46,
        end: 35,
        home: 36,
        pageUp: 33,
        pageDown: 34,
        comma: 188,
        period: 190,
        forwardSlash: 191,
        backSlash: 220,
        semicolon: 186,
        apostrophe: 222,
        leftBracket: 219,
        rightBracket: 221,
        backTick: 192,
        left: 37,
        up: 38,
        right: 39,
        down: 40,
    };
});
